FROM node:18

WORKDIR /app

COPY . .

# instala corretamente o monorepo inteiro
RUN npm install --workspaces --legacy-peer-deps

# entra no frontend
WORKDIR /app/apps/frontend

# garante que next está disponível
RUN npx next build

EXPOSE 3000

CMD ["npx", "next", "start"]
